# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
print("Hello, I'm thrilled to learn PyTorch!")

Hello, I'm thrilled to learn PyTorch!


In [2]:
!nvidia-smi

Mon Feb 10 16:48:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.03                 Driver Version: 561.03         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   55C    P8             15W /  115W |     692MiB /   6144MiB |     17%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
print(torch.__version__)

2.6.0+cpu


## Introduction to Tensors

### Creating Tensors
PyTorch Tensore are being created using `torch.Tensor()` -
https://pytorch.org/docs/stable/tensors.html

#### Scalar

In [8]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [9]:
scalar.ndim

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

#### Vector

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

#### Matrix

In [14]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

#### Tensor

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

In [21]:
TENSOR[0][1]

tensor([3, 4, 5])

### Random Tensors

Why random tensors?

Random tensors are important, because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [22]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6419, 0.8565, 0.9710, 0.0465],
        [0.5016, 0.1980, 0.1732, 0.5398],
        [0.8223, 0.8431, 0.0628, 0.9492]])

In [23]:
random_tensor.ndim

2

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # R, G, B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [25]:
# Create a tensor af all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.range
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors-like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one oh the 3 big errors one will run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

[Precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science))

In [30]:
# Float32 tensor
float_32_tensor = torch.tensor([3., 6., 9.],
                               dtype=None, # what datatype is the tensor, eg float16, uint8, ...
                               device=None, # default="cpu", might be "cuda", this is where the tensor lives
                               requires_grad=False # Track the gradients
                               )
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor,

(tensor([ 9., 36., 81.]),)

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor,

(tensor([3, 6, 9], dtype=torch.int32),)

In [35]:
int_32_tensor * float_16_tensor,

(tensor([ 9., 36., 81.], dtype=torch.float16),)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, one can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, one can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, one can use `tensor.device`

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7061, 0.3869, 0.2355, 0.7859],
        [0.9716, 0.9300, 0.0600, 0.2856],
        [0.2289, 0.9352, 0.0450, 0.4282]])

In [37]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}\n"
      f"Shape of tensor: {some_tensor.shape}\n"
      f"Device of tensor: {some_tensor.device}\n")


tensor([[0.7061, 0.3869, 0.2355, 0.7859],
        [0.9716, 0.9300, 0.0600, 0.2856],
        [0.2289, 0.9352, 0.0450, 0.4282]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu



### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication



In [38]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor - 10

(tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [39]:
tensor * 10, tensor / 10

(tensor([10, 20, 30]), tensor([0.1000, 0.2000, 0.3000]))

In [40]:
# Tryout PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor, 100)

(tensor([10, 20, 30]), tensor([101, 102, 103]))

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise
2. Dot Product

More information on [Mathisfun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer **dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [41]:
# Element-wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
import time

In [43]:
# Dot product
start_time = time.time()
print(torch.matmul(tensor, tensor))
end_time = time.time()
print(f"Time taken: {end_time - start_time}")

tensor(14)
Time taken: 0.0006527900695800781


In [44]:
# Matrix multiplication by hand
start_time = time.time()
value = 0
for i in range(len(tensor)):
  value+=tensor[i] * tensor[i]
print(value)
end_time = time.time()
print(f"Time taken: {end_time - start_time}")

tensor(14)
Time taken: 0.0009949207305908203


#### One of the most common errors in deep learning: shape errors

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B)  # mm: matmul - does not work

To fix the tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [46]:
tensor_B.T, tensor_B, tensor_B.T.shape, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([2, 3]),
 torch.Size([3, 2]))

In [47]:
# The matrix multiplication operation works, when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.T}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-- inner dims must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T).shape

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = tensor([[1, 3, 5],
        [2, 4, 6]]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dims must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


torch.Size([3, 3])

### Finding the min, max, mean, sum ... (tensor aggregation)

In [48]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [49]:
# Find the min
x.min, torch.min(x)

(<function Tensor.min>, tensor(0))

In [50]:
# Find max
x.max, torch.max(x)

(<function Tensor.max>, tensor(90))

In [51]:
# Find mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean

(tensor(45.), <function Tensor.mean>)

In [52]:
# Sum
torch.sum(x)

tensor(450)

### Finding the positional min and max

In [53]:
# Argmax, argmin
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

In [54]:
x[torch.argmax(x)]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensore
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [55]:
# Create a tensor
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [56]:
# Add an extra dimension
x_reshaped = x.reshape(12, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [57]:
x_reshaped = x.reshape(3, 4)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [58]:
# Change the view
z = x.view(4, 3)
z, z.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [59]:
# Changing z changes x (because a view of an tensor shares tho same mem as the original input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.],
         [ 5.,  5.,  6.],
         [ 5.,  8.,  9.],
         [ 5., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]))

In [60]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
         [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
         [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
         [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]]),
 torch.Size([4, 12]))

In [61]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 5.,  5.,  5.,  5.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [ 5.,  5.,  5.,  5.],
         [11., 11., 11., 11.],
         [12., 12., 12., 12.]]),
 torch.Size([12, 4]))

In [62]:
# torch.squeeze() - removes all single dimensions from a target tensor
y = x_reshaped.reshape(1,12)
print(f"Previous tensor: {y}")
print(f"Previous time: {y.shape}")

# Remove extra dimensions from y
y_squeezed = y.squeeze()
print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed}")

Previous tensor: tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]])
Previous time: torch.Size([1, 12])

New tensor: tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.])
New shape: tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.])


In [63]:
# torch.unsqueeze() - adds a single dimension to a target tensor at specific dimension
print(f"Previous tensor: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

# Add an extra dimension with unsqueeze()
w = y_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {w}")
print(f"New shape: {w.shape}")

Previous tensor: tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.])
Previous shape: torch.Size([12])

New tensor: tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]])
New shape: torch.Size([1, 12])


In [64]:
# Add an extra dimension with unsqueeze()
w = y_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {w}")
print(f"New shape: {w.shape}")


New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 5.],
        [ 5.],
        [ 6.],
        [ 5.],
        [ 8.],
        [ 9.],
        [ 5.],
        [11.],
        [12.]])
New shape: torch.Size([12, 1])


In [65]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,200,3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 to 1, 1 to 2, 2 to 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 200, 3])
New shape: torch.Size([3, 224, 200])


In [66]:
x_original[0, 0, 0] = 142

In [67]:
x_permuted[0, 0, 0]

tensor(142.)

### Indexing (selecting data from tensors with indexing)

Indexing with PyTorch is similar to NumPy.

In [68]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [71]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [72]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [73]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [74]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [75]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [76]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [77]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

### PyTorch Tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tonsor to NumPy -> `torch.tensor.numpy()`


In [78]:
# NumPy array to tensor
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
# Change the value of array, what will this do to `tensor`?
array = array + 1 # This allocates a new array and breaks the bond to the old one.
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [80]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [81]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
# Change the tensor, what happens to `numpy_tensor`?
tensor += 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))


PyTorch-Tensoren und NumPy-Arrays können denselben Speicher teilen. In-place Operationen (z. B. +=) an einem wirken sich auf den anderen aus. Verwenden Sie .copy() oder .clone(), um unabhängige Kopien zu erstellen und Änderungen zu isolieren.

## Reproducability - Trying to take random out of random

In short how our neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations oh the data -> again -> again -> ...` 

To reduce the randomness in neural networks and Pytorch comes the concept of **random seed**.

Essentiallz what the random seed does is "flavour" the randomness.

In [83]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A: {random_tensor_A}")
print(f"Tensor B: {random_tensor_B}")
print(f"Tensor A == Tensor B: {random_tensor_A == random_tensor_B}")

Tensor A: tensor([[0.6004, 0.1393, 0.5924, 0.1187],
        [0.4578, 0.3735, 0.1008, 0.4195],
        [0.2059, 0.3251, 0.3879, 0.3101]])
Tensor B: tensor([[0.6574, 0.3977, 0.2522, 0.6930],
        [0.8617, 0.6665, 0.9338, 0.6003],
        [0.0783, 0.6272, 0.4029, 0.2278]])
Tensor A == Tensor B: tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
# Create random but reproduceable tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [85]:
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C: {random_tensor_A}")
print(f"Tensor D: {random_tensor_B}")
print(f"Tensor C == Tensor D: {random_tensor_C == random_tensor_D}")

Tensor C: tensor([[0.6004, 0.1393, 0.5924, 0.1187],
        [0.4578, 0.3735, 0.1008, 0.4195],
        [0.2059, 0.3251, 0.3879, 0.3101]])
Tensor D: tensor([[0.6574, 0.3977, 0.2522, 0.6930],
        [0.8617, 0.6665, 0.9338, 0.6003],
        [0.0783, 0.6272, 0.4029, 0.2278]])
Tensor C == Tensor D: tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra ressoureces:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch optects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunkz dory (good).

### Getting GPUs
1. Google Colab (pro)
2. Use your own
3. Cloud computing (aws, azure,...)

In [86]:
# check for GPU access with PyTorch 
torch.cuda.is_available()

False

In [87]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [88]:
# Count no of gpus
torch.cuda.device_count()

0

📓 For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available else on CPU

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [89]:
# Create e tensor on default (cpu)
tensor = torch.ones(4, 4)

# Print the tensor and it's device
print(tensor, tensor.device)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) cpu


In [90]:
# Create a tensor on GPU (if available)
tensor_cuda_GPU = torch.ones(4, 4).to(device=device)  

# print the tensor and it's device
print(tensor_cuda_GPU)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### 4. Moving tensors back to the CPU

In [91]:
# If tensor is on GPU, one cannot transform it to numpy
try:
  tensor_cuda_GPU.numpy()   
except Exception as e:
    print(e)
    

In [92]:
# To fix the error, move tensor to CPU
tensor_cuda_CPU = tensor_cuda_GPU.to(device="cpu")

# print the tensor and it's device 
print(tensor_cuda_CPU, tensor_cuda_CPU.device)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) cpu


# Exercises & Curriculum

See exercise for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises